name: Setup NodeJS
description: Setup NodeJS with caching
author: 'timo@animo.id'

inputs:
  node-version:
    description: Node version to use
    required: true

runs:
  using: composite
  steps:
    - name: Get cache directory path TBD
      run: echo TO_ADD_CACHE
      shell: bash

branding:
  icon: scissors
  color: purple
