#docker compose -f docker-compose-agent-ipfs.yml up --build -d

##################################################################################
## Docker-Compose for a Single agent + Single IPFS node
##
## Agent: alice
## Ports:
##    Alice   = 3000 / 5002 (HTTP) & 5003 (WS)
##    IPFS    = 8080 (HTTP)
## Network: testnet
##
##################################################################################

services:
  ##################################################################################
  ## Alice #########################################################################
  ##################################################################################

  agent0:
    container_name: alice
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    scale: 0
    depends_on:
      ipfs0:
        condition: service_healthy
    ports:
      - '5002:5002' #5000 is used for AirPlay in MacOS
      - '5003:5003'
      - '3000:3000'
    environment:
      - ENDPOINT='http://alice:5002, ws://alice:5003'
      - IPFS_ORIGIN=http://ipfs0:5001
      - POSTGRES_HOST=veritable-cloudagent-postgres
      - POSTGRES_PORT=5432
    networks:
      - testnet

  ##################################################################################
  ## IPFS ##########################################################################
  ##################################################################################

  ipfs0:
    container_name: ipfs0
    image: ipfs/kubo:release
    ports:
      #     - "4001:4001" # ipfs swarm - expose if needed/wanted
      #     - "5001:5001" # ipfs api - expose if needed/wanted
      - '8080:8080' # ipfs gateway - expose if needed/wanted
    volumes:
      - ipfs0:/data/ipfs
    networks:
      - testnet

  ##################################################################################
  ## PostgreSQL ###########################################################################
  ##################################################################################

  postgres:
    container_name: veritable-cloudagent-postgres
    image: postgres:17.5-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - veritable-cloudagent-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-veritable-cloudagent
    networks:
      - testnet
volumes:
  ipfs0:
  veritable-cloudagent-storage:

networks:
  testnet:
    name: testnet
    driver: bridge
