#docker-compose up --build -d

version: '3.8'

services:
  afj-node01:
    hostname: alice-agent
    container_name: alice-agent
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      # also possible to set values using json
      - ./samples/cliConfig.json:/config.json
    ports:
      - '5002:5002' #5000 is used for AirPlay in MacOS
      - '5003:5003'
      - '3000:3000'
    # or via command line arguments
    command: --ipfs-origin http://localhost:5001 --config /config.json
    networks:
      - testnet
  postgres:
    container_name: alice-agent-postgres
    image: postgres:16.2-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - veritable-cloudagent-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-veritable-cloudagent
    networks:
      - testnet

volumes:
  veritable-cloudagent-storage:

networks:
  testnet:
    name: testnet
    driver: bridge
