#docker-compose up --build -d

services:
  alice:
    hostname: alice-agent
    container_name: alice-agent
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5002:5002' #5000 is used for AirPlay in MacOS
      - '5003:5003'
      - '3000:3000'
    environment: 
      - IPFS_ORIGIN=http://ipfs0:5001
      - POSTGRES_HOST=alice-agent-postgres
      - POSTGRES_PORT=5432
    networks:
      - testnet
  postgres:
    container_name: alice-agent-postgres
    image: postgres:16.3-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - veritable-cloudagent-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - testnet

volumes:
  veritable-cloudagent-storage:

networks:
  testnet:
    name: testnet
    driver: bridge
