#docker-compose up --build -d
version: '3.5'

services:

  afj-node01:
    hostname: alice-agent
    container_name: alice-agent
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      # possible to set values using env variables
      AFJ_REST_LOG_LEVEL: 1
    volumes:
      # also possible to set values using json
      - ./samples/cliConfig.json:/config.json
    ports:
      - '5002:5002' #5000 is used for AirPlay in MacOS
      - '5003:5003'
      - '3000:3000'
    # or via command line arguments
    command: --ipfs-origin http://localhost:5001 --config /config.json
    networks:
      - veritable-testnet

networks:
  veritable-testnet:
    name: veritable-testnet
    driver: bridge
