name: Continuous Integration

on:
  pull_request:
    branches: [main] 
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]

env:
  TEST_AGENT_PUBLIC_DID_SEED: 000000000000000000000000Trustee9
  GENESIS_TXN_PATH: network/genesis/local-genesis.txn

# Make sure we're not running multiple release steps at the same time as this can give issues with determining the next npm version to release.
# Ideally we only add this to the 'release' job so it doesn't limit PR runs, but github can't guarantee the job order in that case:
# "When concurrency is specified at the job level, order is not guaranteed for jobs or runs that queue within 5 minutes of each other."
concurrency:
  group: aries-framework-${{ github.ref }}-${{ github.repository }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-20.04
    name: Validate
    steps:
      - name: Checkout veritable-cloudagent
        uses: actions/checkout@v3

      # setup dependencies
      - name: Setup Libindy
        uses: ./.github/actions/setup-libindy
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Compile
        run: yarn check-types

  integration-test:
    runs-on: ubuntu-20.04
    name: Integration Tests
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout veritable-cloudagent
        uses: actions/checkout@v3
      # setup dependencies
      - name: Setup Libindy
        uses: ./.github/actions/setup-libindy
      - name: Setup Indy Pool
        uses: ./.github/actions/setup-indy-pool
        with:
          seed: ${TEST_AGENT_PUBLIC_DID_SEED}
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run tests for Rest
        run: TEST_AGENT_PUBLIC_DID_SEED=${TEST_AGENT_PUBLIC_DID_SEED} GENESIS_TXN_PATH=${GENESIS_TXN_PATH} yarn test rest --coverage

